CREATE TABLE USER (
    ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USERID VARCHAR(20),
    PASSWORD VARCHAR(20),
    NAME VARCHAR(10),
    NICKNAME VARCHAR(20),
    PHONENUMBER VARCHAR(15),
    EMAIL VARCHAR(20),
    REQTIME DATETIME) CHARACTER SET utf8;

CREATE TABLE BOARD (
    ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(20),
    CONTENT VARCHAR(255),
    WRITER VARCHAR(20),
    WRITEDATE DATETIME) CHARACTER SET utf8;